{{- if or .Values.postgres.enabled  .Values.digger.postgres.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "digger-backend.fullname" . }}-postgres-secret
type: Opaque
data:
  {{- if and .Values.postgres.secret.password (not .Values.postgres.secret.useExistingSecret) }}
  postgres-password: {{ .Values.postgres.secret.password | b64enc | quote }}
  {{- else }}
  postgres-password: {{ .Values.digger.postgres.password | b64enc | quote }}
  {{- end }}
{{- end }}
